In [1]:
import numpy as np

In [5]:
n=np.array([5,6,7])
n.ndim

1

In [3]:
a=np.array([[5,6,9],[8,2,6],[4,6,9]])
a.ndim

2

In [4]:
a.itemsize

4

In [7]:
a.dtype

dtype('int32')

In [8]:
b=np.array([[5,6,9],[8,2,6],[4,6,9]], dtype=np.float64)
b.dtype

dtype('float64')

In [9]:
b

array([[5., 6., 9.],
       [8., 2., 6.],
       [4., 6., 9.]])

In [10]:
b.size

9

In [11]:
a.shape

(3, 3)

In [12]:
b=np.array([[5,6,9],[8,2,6],[4,6,9]], dtype=complex)
b

array([[5.+0.j, 6.+0.j, 9.+0.j],
       [8.+0.j, 2.+0.j, 6.+0.j],
       [4.+0.j, 6.+0.j, 9.+0.j]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
l=range(5)
l

range(0, 5)

In [17]:
np.arange(1,5)

array([1, 2, 3, 4])

In [18]:
np.arange(1,5,2)

array([1, 3])

In [19]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [21]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [22]:
b

array([[5.+0.j, 6.+0.j, 9.+0.j],
       [8.+0.j, 2.+0.j, 6.+0.j],
       [4.+0.j, 6.+0.j, 9.+0.j]])

In [23]:
b.shape

(3, 3)

In [25]:
b

array([[5.+0.j, 6.+0.j, 9.+0.j],
       [8.+0.j, 2.+0.j, 6.+0.j],
       [4.+0.j, 6.+0.j, 9.+0.j]])

In [31]:
b.ravel()

array([5.+0.j, 6.+0.j, 9.+0.j, 8.+0.j, 2.+0.j, 6.+0.j, 4.+0.j, 6.+0.j,
       9.+0.j])

In [32]:
b.min()

(2+0j)

In [33]:
b.max()

(9+0j)

In [34]:
b.sum()

(55+0j)

In [35]:
b.ravel()

array([5.+0.j, 6.+0.j, 9.+0.j, 8.+0.j, 2.+0.j, 6.+0.j, 4.+0.j, 6.+0.j,
       9.+0.j])

In [36]:
b

array([[5.+0.j, 6.+0.j, 9.+0.j],
       [8.+0.j, 2.+0.j, 6.+0.j],
       [4.+0.j, 6.+0.j, 9.+0.j]])

In [37]:
c=np.array([[5,6,9],[8,2,6],[4,6,9]])
c

array([[5, 6, 9],
       [8, 2, 6],
       [4, 6, 9]])

In [39]:
c.sum(axis=0)

array([17, 14, 24])

In [40]:
c.sum(axis=1)

array([20, 16, 19])

In [41]:
np.sqrt(c)

array([[2.23606798, 2.44948974, 3.        ],
       [2.82842712, 1.41421356, 2.44948974],
       [2.        , 2.44948974, 3.        ]])

In [42]:
np.std(c)

2.1829869671542776

In [44]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [45]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [46]:
x+y

array([[ 6,  8],
       [10, 12]])

In [48]:
x.dot(y) #product

array([[19, 22],
       [43, 50]])