In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [3]:
a1+a2

array([5, 7, 9])

In [4]:
a1-a2

array([-3, -3, -3])

In [5]:
a1*a2

array([ 4, 10, 18])

In [6]:
a1/a2

array([0.25, 0.4 , 0.5 ])