In [1]:
import numpy as np

In [2]:
n=[6,7,8]

In [3]:
n[0:2]

[6, 7]

In [4]:
n[-1]

8

In [5]:
a=np.array([6,7,8])

In [6]:
a[0:2]

array([6, 7])

In [7]:
a[-1]

8

In [8]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])

In [9]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [10]:
a[1,2]

3

In [12]:
a[2,1]

3

In [13]:
a[0:2,2]

array([8, 3])

In [14]:
a[-1]

array([9, 3, 2])

In [15]:
a[-1,0:2]

array([9, 3])

In [16]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [17]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [18]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [19]:
a=np.arange(6).reshape(3,2)

In [20]:
b=np.arange(6,12).reshape(3,2)

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [26]:
a=np.arange(30).reshape(2,15)

In [27]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [28]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [29]:
result=np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [30]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [31]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [33]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [35]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [40]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])